spring.application.name=todo

spring.datasource.url=jdbc:mysql://altaria.proxy.rlwy.net:33938/railway
spring.datasource.username=root
spring.datasource.password=JUwbbviupDiEderijGLZevZKZmlGTWgz

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=3030